update logic to fail pipeline if cfn-guard fails

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -189,7 +189,12 @@ runs:
       if: inputs.policy_as_code_provider != 'None' && inputs.job_type == 'Validate'
       working-directory: action
       shell: bash
-      run: python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ inputs.branch_type == 'major' && inputs.aws_account_number || '123456789012' }} --job Validate --config_file ${{ inputs.config_file_path }} --deployment_folder ${{ inputs.deployment_folder_path }} --rules_folder ${{ inputs.rules_folder_path }}
+      run: |
+        RESULT=$(python -m scripts.deploy --branch ${{ github.ref_name }} --account_number ${{ inputs.branch_type == 'major' && inputs.aws_account_number || '123456789012' }} --job Validate --config_file ${{ inputs.config_file_path }} --deployment_folder ${{ inputs.deployment_folder_path }} --rules_folder ${{ inputs.rules_folder_path }})
+        if [ $RESULT -ne 0 ]; then
+          echo "ERROR: See logs for details."
+          exit $RESULT
+        fi
     - name: Deploy Templates
       if: inputs.branch_type == 'major' && inputs.job_type == 'Deploy'
       working-directory: action
